-- SQL Statement that used in the cart.db

-- create/ open database

-- create table

-- schema :
-- CATEGORIES
CREATE TABLE CATEGORIES (
 CATID INTEGER PRIMARY KEY,
 NAME TEXT
);
-- PRODUCTS
-- Required columns: pid (primary key), catid, name, price, description
CREATE TABLE PRODUCTS (
 PID INTEGER PRIMARY KEY,
 CATID INTEGER,
 NAME TEXT,
 PRICE REAL,
 DESCRIPTION TEXT,
 QUANTITY INTEGER,
 FOREIGN KEY(CATID) REFERENCES CATEGORIES(CATID)
);

-- USERS
CREATE TABLE USERS (
 USERID INTEGER PRIMARY KEY,
 USERNAME VARCHAR(20),
 EMAIL VARCHAR(100),
 SALT TEXT,
 SHPWD TEXT,
 ADMINFLAG INTEGER
);

